version: '3'

services:
  web:
    build: ./web
    ports:
      - 80:80
    command: sh /init.sh
    volumes:
      - .:/var/www/html
      - ./web/sites:/etc/apache2/sites-enabled
      - ./web/init.sh:/init.sh
      - ./web/logs/:/var/log/apache2
    links:
      - db_demo
      - redis
  db_demo:
    image: mysql:5.7
    volumes:
      - datastore:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=learn-laravel-60
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  redis:
    image: redis

volumes:
  datastore: {}
